spring:
        profiles:
                active:
                - dev
---
server:
    port: 8001
    
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml   # mybatis配置文件所在路径
    type-aliases-package: com.hxb.springcloud.entites    # 所有Entity别名类别配置
    mapper-locations: classpath:mybatis/mapper/**/*.xml     # mapper映射文件
    
spring:
    profiles: dev      # 设置开发环境
    application:
        name: microservicecloud-dept                     # 应用的名称，也是也是微服务的名称
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource     # 当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver       # mysql驱动包
        url: jdbc:mysql://localhost:3306/cloudDB01       # 数据库名称
        username: root
        password: 123456
        dbcp2:
            min-idle: 5                  # 数据库连接池的最小维持连接数
            initial-size: 5              # 初始化连接数
            max-total: 5                 # 最大连接数
            max-wait-millis: 200         # 等待链接获取的最大超时时间

eureka:
    client: # 将客户端注册到eureka服务列表中
        service-url:
            #(单机版的该服务的配置)
            defaultZone: http://localhost:7001/eureka
            #(集群版的该服务配置)
            #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:   
        instance-id: microservicecloud-dept8001 # 微服务的别名，便于在eureka中查看
        prefer-ip-address: true    # 访问路径可以显示IP地址，当鼠标移动到名称时，左下角显示IP

info:
    app.name: hxb-microservicecloud
    company.name: www.hxb.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$
---
server:
    port: 8001
    
mybatis:
    config-location: classpath:mybatis/mybatis.cfg.xml   # mybatis配置文件所在路径
    type-aliases-package: com.hxb.springcloud.entites    # 所有Entity别名类别配置
    mapper-locations: classpath:mybatis/mapper/**/*.xml     # mapper映射文件
    
spring:
    profiles: test      # 设置开发环境
    application:
        name: microservicecloud-dept                     # 应用的名称，也是也是微服务的名称
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource     # 当前数据源操作类型
        driver-class-name: org.gjt.mm.mysql.Driver       # mysql驱动包
        url: jdbc:mysql://localhost:3306/cloudDB01       # 数据库名称
        username: root
        password: 123456
        dbcp2:
            min-idle: 5                  # 数据库连接池的最小维持连接数
            initial-size: 5              # 初始化连接数
            max-total: 5                 # 最大连接数
            max-wait-millis: 200         # 等待链接获取的最大超时时间

eureka:
    client: # 将客户端注册到eureka服务列表中
        service-url:
            #(单机版的该服务的配置)
            defaultZone: http://localhost:7001/eureka
            #(集群版的该服务配置)
            #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
    instance:   
        instance-id: microservicecloud-dept8001 # 微服务的别名，便于在eureka中查看
        prefer-ip-address: true    # 访问路径可以显示IP地址，当鼠标移动到名称时，左下角显示IP

info:
    app.name: hxb-microservicecloud
    company.name: www.hxb.com
    build.artifactId: $project.artifactId$
    build.version: $project.version$



